---
version: 2
branches:
  only:
    - master
jobs:
  build:
    working_directory: /var/app
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: yarn install --force
      - run: git config --global user.email "circleci@circleci.com"
      - run: git config --global user.name "circleci"
      - run: mkdir -p build/Release
      - run: cp -rv .circleci/config.yml build/Release/circle.yml
      - run: yarn run -- deploy
...
