---
version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: /var/app
    docker:
      - image: node:latest
    steps:
      - run: apt-get update -qq && apt-get install -qy libelf1
      - checkout
      - run: npm install
      - run: git config --global user.email "circleci@circleci.com"
      - run: git config --global user.name "circleci"
      - run: mkdir -p build/Release
      - run: cp -rv .circleci/config.yml build/Release/circle.yml
      - run: npm run deploy
  test:
    branches:
      ignore:
        - master
        - gh-pages
    working_directory: /var/app
    docker:
      - image: node:latest
    steps:
      - run: apt-get update -qq && apt-get install -qy libelf1
      - checkout
      - run: npm install
      - run: npm test
...
